name: Render Server keep-alive

on:
  schedule:
    - cron: '*/14 * * * *'
  workflow_dispatch:

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: |
          curl -fso /dev/null -w "Backend status: %{http_code}\n" https://esg-weather-tracker.onrender.com/api/load || echo 'Backend did not respond'
      
      - name: Ping frontend
        run: |
          curl -fso /dev/null -w "Frontend status: %{http_code}\n" https://esg-weather-report.onrender.com || echo 'Frontend did not respond'