name: Register Weather Data

on:
  schedule:
    - cron: '10 10 * * *'
  workflow_dispatch:

jobs:
  register:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        run: uv python install 3.14

      - name: Installing dependencies
        run: uv sync --frozen

      - name: Registering weather
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
          LATITUDE: ${{ secrets.LATITUDE }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
        run: uv run -m src.main
